name: Build and Push Flask App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Print tag
        run: |
          echo "Current tag: ${{ github.ref_name }}"
      # 检出代码
      - name: 检出代码
        uses: actions/checkout@v4

      # 登录阿里云 ACR
      - name: 登录阿里云 ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3



      # 构建并推送多平台 Docker 镜像
      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/flask-info:${{ github.ref_name }}
